version: '3'
services:
  dynamodb_local:
    container_name: jedlik-demo-dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: [-jar, DynamoDBLocal.jar, -sharedDb]
  api:
    depends_on:
      - dynamodb_local
    container_name: jedlik-demo-api
    image: node:16-alpine
    volumes:
      - .:/usr/service
    working_dir: /usr/service
    ports:
      - 3000:3000
    command: [npx, nodemon, src/index.ts]
